Repository fedora-infra/pagure-exporter, pull requests merged in 2023-10, with the labels that each got.

#13 Adding pre-commit into repo
  .idea/inspectionProfiles/profiles_settings.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/protop2g.iml
  .idea/vcs.xml
  .pre-commit-config.yaml
  README.md
  doformat.sh
  poetry.lock
  protop2g/work/stat.py
  pyproject.toml
Labels: documentation, enhancement, dependencies, github-action

#5 Transferring issue tickets from the source namespace to the destination namespace
  .idea/protop2g.iml
  README.md
  protop2g/conf/standard.py
  protop2g/main.py
  protop2g/view/tkts.py
  protop2g/work/keep.py
  protop2g/work/stat.py
  protop2g/work/tkts.py
Labels: enhancement

#17 Reformat the codebase and add exceptions
  protop2g/conf/standard.py
  protop2g/view/tkts.py
  protop2g/work/tkts.py
Labels: enhancement

#20 Add documentation for the `--commit` option
  README.md
Labels: documentation

#27 Setup codebase testing with an initial set of tests
  poetry.lock
  protop2g/main.py
  pyproject.toml
  test/__init__.py
  test/test_main.py
Labels: hacktoberfest

#30 Add CI/CD support using GitHub Actions
  .github/workflows/main.yml
  .pre-commit-config.yaml
  poetry.lock
  protop2g/conf/standard.py
  protop2g/main.py
  protop2g/view/stat.py
  protop2g/work/repo.py
  protop2g/work/stat.py
  protop2g/work/tkts.py
  pyproject.toml
  test/test_main.py
  tox.ini
Labels: hacktoberfest

#39 Include more test cases to check issue ticket operations
  protop2g/conf/standard.py
  protop2g/view/repo.py
  protop2g/view/tkts.py
  protop2g/work/keep.py
  test/__init__.py
  test/test_main.py
  test/test_repo.py
  test/test_tkts.py
  test/test_unit_repo.py
  test/test_unit_tkts.py
Labels: enhancement

#44 Add more description for the software application
  pyproject.toml
Labels: enhancement

#49 Version bump the RPM specfile to v0.1.1
  pagure-exporter.spec
Labels: enhancement
