Repository fedora-infra/pagure-exporter, pull requests merged in 2024-03, with the labels that each got.

#110 Clean up after the removal of requests-based GitLab interactions
  pagure_exporter/conf/standard.py
  pagure_exporter/view/tkts.py
  test/cassettes/test_stat/test_stat_destdata_obtninfo[Checking for possible errors while attempting to authenticate in the destination namespace using wrong credentials].yaml
  test/cassettes/test_tkts/test_main_tkts[Transferring issue tickets from a source namespace that does not exist].yaml
  test/cassettes/test_tkts/test_main_tkts[Transferring issue tickets to a destination namespace that does not exist].yaml
  test/cassettes/test_tkts/test_main_tkts[Transferring issue tickets with FULL status along with comments but without labels, without privacy and without states].yaml
  test/cassettes/test_tkts/test_main_tkts[Transferring issue tickets with FULL status along with labels but without states, without privacy and without comments].yaml
  test/cassettes/test_tkts/test_main_tkts[Transferring issue tickets with FULL status along with states but without comments, without privacy and without labels].yaml
  test/cassettes/test_tkts/test_main_tkts[Transferring issue tickets with FULL status without labels, without states, without privacy and without comments the identities of which fall in the given range].yaml
  test/cassettes/test_tkts/test_main_tkts[Transferring issue tickets with FULL status without labels, without states, without privacy and without comments the identities of which fall in the given selection].yaml
  test/cassettes/test_tkts/test_main_tkts[Transferring issue tickets with FULL status without labels, without states, without privacy and without comments].yaml
  test/cassettes/test_tkts/test_main_tkts[Transferring issue tickets with OPEN status along with comments but without labels, without privacy and without states].yaml
  test/cassettes/test_tkts/test_main_tkts[Transferring issue tickets with OPEN status along with labels but without states, without privacy and without comments].yaml
  test/cassettes/test_tkts/test_main_tkts[Transferring issue tickets with OPEN status along with privacy but without states, without comments and without labels].yaml
  test/cassettes/test_tkts/test_main_tkts[Transferring issue tickets with OPEN status along with states but without comments, without privacy and without labels].yaml
  test/cassettes/test_tkts/test_main_tkts[Transferring issue tickets with OPEN status without labels, without states, without privacy and without comments the identities of which fall in the given range].yaml
  test/cassettes/test_tkts/test_main_tkts[Transferring issue tickets with OPEN status without labels, without states, without privacy and without comments the identities of which fall in the given selection].yaml
  test/cassettes/test_tkts/test_main_tkts[Transferring issue tickets with OPEN status without labels, without states, without privacy and without comments].yaml
  test/cassettes/test_tkts/test_main_tkts[Transferring issue tickets with SHUT status along with comments but without labels, without privacy and without states].yaml
  test/cassettes/test_tkts/test_main_tkts[Transferring issue tickets with SHUT status along with labels but without states, without privacy and without comments].yaml
  test/cassettes/test_tkts/test_main_tkts[Transferring issue tickets with SHUT status along with privacy but without states, without comments and without labels].yaml
  test/cassettes/test_tkts/test_main_tkts[Transferring issue tickets with SHUT status along with states but without comments, without privacy and without labels].yaml
  test/cassettes/test_tkts/test_main_tkts[Transferring issue tickets with SHUT status without labels, without states, without privacy and without comments the identities of which fall in the given range].yaml
  test/cassettes/test_tkts/test_main_tkts[Transferring issue tickets with SHUT status without labels, without states, without privacy and without comments the identities of which fall in the given selection].yaml
  test/cassettes/test_tkts/test_main_tkts[Transferring issue tickets with SHUT status without labels, without states, without privacy and without comments].yaml
  test/cassettes/test_tkts/test_main_tkts[Transferring particular issue tickets with OPEN status along with states and comments but without labels and without privacy].yaml
  test/cassettes/test_tkts/test_main_tkts[Transferring particular issue tickets with OPEN status without labels, without states, without privacy and without comments when SHUT status is prescribed].yaml
  test/cassettes/test_tkts/test_main_tkts[Transferring particular issue tickets with SHUT status along with states and comments but without labels and without privacy].yaml
  test/cassettes/test_unit_tkts/test_unit_getcount[Attempting to count issue tickets from a valid issue tracker of longer length].yaml
  test/cassettes/test_unit_tkts/test_unit_getcount[Attempting to count issue tickets from a valid issue tracker of smaller length].yaml
  test/cassettes/test_unit_tkts/test_unit_getcount_expt[Attempting to count issue tickets from an existing issue tracker on an existing forge].yaml
  test/cassettes/test_unit_tkts/test_unit_getcount_expt[Attempting to count issue tickets from an invalid issue tracker on an existing forge].yaml
  test/cassettes/test_unit_tkts/test_unit_itercmts[Attempting to migrate an existing comment to an existing namespace].yaml
  test/cassettes/test_unit_tkts/test_unit_iteriden[Attempting to probe the issue ticket with the existing identity with matching status].yaml
  test/cassettes/test_unit_tkts/test_unit_iteriden[Attempting to probe the issue ticket with the existing identity with mismatch status].yaml
  test/cassettes/test_unit_tkts/test_unit_iteriden[Attempting to probe the issue ticket with the invalid identity].yaml
  test/cassettes/test_unit_tkts/test_unit_iteriden_expt[Attempting to iterate through the first page from an invalid issue tracker on an existing forge].yaml
  test/cassettes/test_unit_tkts/test_unit_iteriden_expt[Attempting to probe the issue ticket with the existing identity on an existing issue tracker on an existing forge].yaml
  test/cassettes/test_unit_tkts/test_unit_iterpage[Attempting to iterate through the first page from an existing issue tracker for OPEN tickets].yaml
  test/cassettes/test_unit_tkts/test_unit_iterpage[Attempting to iterate through the first page from an existing issue tracker for SHUT tickets].yaml
  test/cassettes/test_unit_tkts/test_unit_iterpage[Setting an invalid `pagesize` value].yaml
  test/cassettes/test_unit_tkts/test_unit_iterpage_expt[Attempting to iterate through the first page from an existing issue tracker on an existing forge].yaml
  test/cassettes/test_unit_tkts/test_unit_iterpage_expt[Attempting to iterate through the first page from an invalid issue tracker on an existing forge].yaml
  test/cassettes/test_unit_tkts/test_unit_iterstat[Attempting to migrate status of an existing issue ticket when requested on an existing namespace].yaml
  test/cassettes/test_unit_tkts/test_unit_iterstat[Attempting to migrate status of an invalid issue ticket when requested on an existing namespace].yaml
  test/cassettes/test_unit_tkts/test_unit_itertkts[Attempting to migrate an existing issue ticket with tags to an existing namespace].yaml
  test/cassettes/test_unit_tkts/test_unit_itertkts[Attempting to migrate an existing issue ticket without tags to an existing namespace].yaml
  test/test_unit_tkts.py
Labels: bug

#116 add Packit support
  .packit.yaml
Labels: enhancement, good first issue

#120 Bump version from v0.1.2 to v0.1.3
  pyproject.toml
Labels: enhancement

#123 Facilitate Packit support for Fedora Linux 38 and Fedora Linux 39
  .fmf/version
  .packit.yaml
  packit/installation/main.fmf
  poetry.lock
  pyproject.toml
Labels: dependencies
